### ISSUE TITLE
Command validation solution

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/event-sourcing#41]
We've discussed a few options now, here's the history:

I wrote on 1st December 2015:
> Usually there's a field that determines the uniqueness of an aggregate, and really is not a business rule, but should be as close to the domain as possible, which for our implementation would be the Space.eventSourcing.Router. This in my mind is analogous to putting a unique constraint at the DB. 

> Projections allow a highly optimised and indexed lookup table to be generated, so the solution should encompass this given we're hitting it every time an initializing command is sent. Rejection of such command should raise an exception, and I feel it is a domain exception, it's just we don't need an aggregate to tell us this has occurred. 

> I believe we can address this using an API on the Router like 'uniqueFields' (array of objects?) which causes a new projection to be created and managed in the background.

@DominikGuzei responded:

> sounds great, the only problem to solve is how the projection knows which commands / events it should listen to for generating the index. Maybe it should be a method you can define per constraint, because we probably also want to customize the error message.

In discussion with @qejk lately and in combination with the [Commits now being more easily query-able](https://github.com/meteor-space/event-sourcing/pull/37) it seems that a generic command validation layer will be a decent option over the automated projected lookups.

@qejk can you give us an update here when you work through the current prototype?

**Comment by qejk** [comment]
Could you please in some simple terms explain the end goal what you want to archive?
How I currently understand scenario: 
> if someones tries to fire up command that is essentially `initializingMessage` with already existing `Guid` `Aggregate` instance -> exception should be thrown

Currently system does allow that? (idk if I’ve got the intentions right)

**Comment by rhyslbw** [comment]
The idea here is was that we could set a unique key, which the system then uses to manage a projection, allowing the router to do a lookup before creating a new Aggregate. This was needed because we were focussed on trying to automate the Router as much as possible using simple mappings, which really complicates validation, not just uniqueness validation. So I think we can just consider that we would check for uniqueness in a standard command validation function

**Comment by rhyslbw** [comment]
> Currently system does allow that?
No the system will currently throw an error, we we're really wanting `Space.domain.Exception` to be thrown if a uniqueness rule is invalidated.

**Comment by qejk** [comment]
Before I write a longer explanation, so in ever more simpler terms (do I get this correct?):

Scenario: 
> We have a Person aggregate, we want to have only one person in system with corresponding NIN (national id)

so essentially this does not relate to internals of ES workings, but domain itself: like typical real word examples of unique keys ISBN, NIN, TIN (tax id) etc?

**Comment by rhyslbw** [comment]
Correct. If we can work on this in `space:domain` then the ES router can depend on instances of validators (for example). I may have created this issue in the wrong repo :smile:

**Comment by qejk** [comment]
Simplifing DDD, I like it. However (if I get this right):

> Projections allow a highly optimized and indexed lookup table to be generated, so the solution should encompass this given we're hitting it every time an initializing command is sent. Rejection of such command should raise an exception, and I feel it is a domain exception, it's just we don't need an aggregate to tell us this has occurred.

There are valid scenarios, where unique data is changed - the simplest I can think of is username. If we listen only for `initializingMessage`, then if aggregate `User` has  something in lines of `UpdateUsername` command that can change username - were screwed.

If we create Projection with full structure, and listen to every single event there is on `Aggregate` - then we will end up with thing we essentially want in first place. The last possible version of aggregate. However again thats not efficient.

There is no other way around since if we allow only few fields, few events, and then later in 1 month want to add another field - were going to require to rebuild that (if migrations are fine - then ok).

The other way around is adding command validator, that can fire up app/domain layer just before running command handler - where its up to developer to create appropriate structure for validation using application's `Repository` pattern - and talking with persistence.


That aside, validating command: 

The best way to hook up for it is my opinion to handlers at `Space.messaging.CommandBus`, using decorator over existing handler for specific, existing command handler - and then overriding that command handler using `overrideHandler(command, handler)` https://github.com/meteor-space/messaging/blob/master/source/command_bus.coffee#L35 - its the simplest approach.

By doing so, we can have unlimited wrappers for each commands handlers, however we need to take into account that the last wrapper set on application layer - will fire first, so it can cause confusion sometimes if set improperly. 

Proposed solution above I'm running: https://github.com/qejk/messaging/blob/feature/command-processor/source/command-processor.coffee#L44

**Comment by qejk** [comment]
We could also run trough all events `fields` that are mapped on aggregate to find appropriate ones having that `field`, then only subscribe to those who have this `field` - same goes for commands.

This would be highly opinionated however.

**Comment by rhyslbw** [comment]
Great I agree. I'll make an issue on `space:messaging` and we can continue the discussion on the  underlying command bus feature, which IMO should be considered _middleware_

Will close this now so we can focus on the feature in `space:messaging`, and if we see a logical abstraction can re-open this.
